name: Update badges

on:
  schedule:
    # Runs at 0am UTC every day
    - cron: "50 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "My commit message to update badges"
          CREDLY_USER: <asilva-jr>
          CREDLY_SORT: POPULAR

